REVOKE ALL ON SCHEMA public FROM PUBLIC;

DROP ROLE IF EXISTS __DB_APP_USER__;
CREATE ROLE __DB_APP_USER__ WITH LOGIN PASSWORD '__DB_APP_PASSWORD__';

GRANT CONNECT ON DATABASE __POSTGRES_DB__ TO __DB_APP_USER__;
GRANT USAGE ON SCHEMA public TO __DB_APP_USER__;

GRANT SELECT ON vw_Topn_prodcuts TO __DB_APP_USER__;
GRANT SELECT ON vw_unsold_products TO __DB_APP_USER__;
GRANT SELECT ON vw_Greater_Buyers TO __DB_APP_USER__;
GRANT SELECT ON vw_Stock_Categories TO __DB_APP_USER__;
GRANT SELECT ON vw_participacion_producto TO __DB_APP_USER__;